#!/usr/bin/env python3
import fileinput
import json
import sys


def main():
    for line in fileinput.input():
        data = {}
        for word in line.rstrip("\n").split(sep="\t"):
            pair = word.split(sep=":", maxsplit=1)
            if len(pair) == 2 and pair[0] != "":
                data[pair[0]] = pair[1]
        sys.stdout.write(json.dumps(data, ensure_ascii=False) + "\n")


if __name__ == "__main__":
    main()

